header_pages:
  - index.md
  - about.md
  - resources.md

posts:
  - _posts/2020-05-01-upgrading-ubuntu.md
  - _posts/2020-11-11-ts-arima.md
  - _posts/2020-07-11-Understanding-Generative-Adversarial-Networks.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-console
